## prefix below must be set in @Configuration/@ConfigurationProperties
twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - Elasticsearch
  welcome-message: Hello and welcome to this Microservices Demo
## Lecture 9 ignored as @ $100 pm a Twitter account that can read tweets is not viable enable-v2-tweets is included to see @ConditionalOnExpression
  enable-v2-tweets: false
  enable-mock-tweets: true
  mock-min-tweet-length: 1
  mock-max-tweet-length: 2
  mock-sleep-ms: 10000
## Hard-coded configuration values for variables defined and referred to in RetryConfigData app-config-data and RetryConfig common-config
retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000
## Hard-coded config values for KafkaConfigData class in module app-config-data as defined in docker-compose files
kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url: http://localhost:8081
  schema-registry-url-key: schema.registry.url
  topic-name: twitter-topic
  topic-names-to-create:
    - twitter-topic
  num-of-partitions: 3
  replication-factor: 3

  


  