## prefix below must be set in @Configuration/@ConfigurationProperties
twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - Elasticsearch
  welcome-message: Hello and welcome to this Microservices Demo
## Lecture 9 ignored as @ $100 pm a Twitter account that can read tweets is not viable enable-v2-tweets is included to see @ConditionalOnExpression
  enable-v2-tweets: false
  enable-mock-tweets: true
  mock-min-tweet-length: 1
  mock-max-tweet-length: 2
  mock-sleep-ms: 10000
## Hard-coded configuration values for variables defined and referred to in RetryConfigData app-config-data and RetryConfig common-config
retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000

  