#### 1-2 Working with security bypassed
## 1  GetMapping("/")
GET http://localhost:8183/elastic-query-service/documents/
Accept: application/json
content-type: application/json

###
## 2 GetMapping("/{id}")
GET http://localhost:8183/elastic-query-service/documents/?id=4
Accept: application/json
content-type: application/json

###
## 3
POST http://localhost:8183/elastic-query-service/documents/get-document-by-text/
Accept: application/json
content-type: application/json

{
  "id": "4",
  "text": "test multi word"
}
### 3 returning:
##        {
##  "timestamp": "2023-08-08T03:51:21.863+00:00",
##  "status": 403,
##  "error": "Forbidden",
##  "message": "",
##  "path": "/elastic-query-service/documents/get-document-by-text/"
##}
###
