### 1 GetMapping("/")
# @no-cookie-jar
GET http://localhost:8183/elastic-query-service/documents/
Authorization: basic {{username}} {{password}}
Accept: application/vnd.api.v1+json
content-type: application/json

### 2 v1 media versioning api example here 2b getmapping("/{id}") vnd.api.v1+json
# @no-cookie-jar
GET http://localhost:8183/elastic-query-service/documents/1
authorization: basic {{username}} {{password}}
accept: application/vnd.api.v1+json
content-type: application/json

### 2 v2 getmapping("/{id}") media versioning api example vnd.api.v2+json
# @no-cookie-jar
GET http://localhost:8183/elastic-query-service/documents/1
authorization: basic {{username}} {{password}}
accept: application/vnd.api.v2+json
content-type: application/json

### 3 postmapping("/get-document-by-text")
# @no-cookie-jar
POST http://localhost:8183/elastic-query-service/documents/get-document-by-text/
authorization: basic {{username}} {{password}}
accept: application/vnd.api.v1+json
content-type: application/json

{
  "text": "test"
}
